Update memory.rb
Comment out swap as it causes an error on some CentOS 7 systems:

/opt/graphital/graphital.d/memory.rb:10:in `<main>': undefined method `split' for nil:NilClass (NoMethodError)

Need to investigate the issue in more depth - this is more of a temporary hack, than anything.